- hosts: all
  become: true
  vars:
    k8s_action: none
    role: none
  roles:
    - geerlingguy.docker
    - kubernetes

- hosts: k8s-primary-master
  become: true
  vars:
    k8s_action: init
    role: master
    token: beec8f.d58d453fb6470881
  roles:
    - kubernetes

#- hosts: k8s-masters
#  become: true
#  vars:
#    k8s_action: join
#    role: master
#    token: beec8f.d58d453fb6470881
#  roles:
#    - kubernetes

- hosts: k8s-workers
  become: true
  vars:
    k8s_action: join
    role: worker
    token: beec8f.d58d453fb6470881
  roles:
    - kubernetes
