# initialize a new kubernetes cluster

- name: Init Kubernetes cluster
  shell: kubeadm reset

- name: Init Kubernetes cluster
  shell: |
    kubeadm init --pod-network-cidr 10.244.0.0/16 \
                 --token {{ token }}

- name: Create Kubernetes config directory
  become: false
  file: path="~/.kube/" state=directory

- name: Change permissions of .kube/config
  file: path=/etc/kubernetes/admin.conf mode=0775

- name: Copy admin.conf to Home directory
  when: init_cluster
  become: false
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "~/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    remote_src: True


