
# initialize a new kubernetes cluster

- name: Reset k8s cluster
  shell: kubeadm reset

- name: Join Kubernetes cluster
  shell: |
    kubeadm join --token {{ token }} \
                 --discovery-token-unsafe-skip-ca-verification \
                 {{ groups['k8s-primary-master'][0] }}:6443 
