---
# tasks file for common role
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
- name: Disable SELinux
  selinux:
    policy: targeted
    state: permissive
- name: Add kubernetes yum repo
  yum_repository:
    name: kubernetes
    description: kubernetes upstream repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: no
- name: Install kubernetes components
  yum:
    name: "{{ item }}"
  with_items:
    - kubelet
    - kubeadm
    - kubectl
- name: Disable iptables
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  notify:
    - reload sysctl
- name: copy kubeadm service file for kubelet
  copy:
    src: 10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
- name: start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: True
    
- name: create kubernetes cluster
  include_tasks: init.yml
  when: k8s_action == 'init'

- name: join workers to cluster
  include_tasks: join_worker.yml
  when: k8s_action == 'join'
 
#- name: join additional master to cluster
#  include_tasks: join_master.yml
#  when: k8s_action == 'join' && role == 'master'
